[package]
name = "tantivy-cli"
version = "0.13.0"
authors = ["Paul Masurel <paul.masurel@gmail.com>"]

description = """Command line interface for Tantivy, a search engine library."""
documentation = "https://github.com/tantivy-search/tantivy-cli"
homepage = "https://github.com/tantivy-search/tantivy-cli"
repository = "https://github.com/tantivy-search/tantivy-cli"

readme = "README.md"
keywords = ["search", "information", "retrieval"]
license = "MIT"
edition = "2018"

[dependencies]
time = "0.1"
iron = "0.4"
staticfile = "0.3"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
persistent="0.2"
clap = "2"
ansi_term = "0.8"
urlencoded = "0.4"
mount = "0.2"
chan = "0.1"
futures = "0.3"
slog-term = "2.6"
slog-async = "2.5"
slog-json = "2.3"
tantivy = {path = "../tantivy"}

[[bin]]
name = "tantivy"
path = "src/main.rs"

[profile.release]
opt-level = 3
debug = true
debug-assertions = false
lto = true
